version: "3.8"

services:
  postgresql-gitea:
    image: ${POSTGRES_IMAGE}
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ENABLE_TLS=no
    ports:
      - "5433:5432"
    volumes:
      - gitea-postgresql-data:/bitnami/postgresql
    restart: unless-stopped 
    networks:
      gitea:
  
  gitea:
    image: ${GITEA_IMAGE}
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgresql-gitea:5433
      - GITEA__database__NAME=${POSTGRESQL_DATABASE}
      - GITEA__database__USER=${POSTGRESQL_USERNAME}
      - GITEA__database__PASSWD=${POSTGRESQL_USERNAME}
    restart: unless-stopped 
    ports:
      - '3000:3000'
      - '2222:2222'
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgresql-keycloak
    networks:
      - proxy
      - gitea
    security_opt:
      - no-new-privileges:true

volumes:
  gitea-postgresql-data:
  gitea-data:

networks:
  gitea:
  proxy: 
    external: true