version: "3.8"

services:     
  vault:
    image: ${VAULT_IMAGE}
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_LOG_LEVEL: ${VAULT_LOG_LEVEL}
    ports:
      - ${VAULT_PORT}:8200
    restart: always
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data
      - ./vault/policy.json:/vault/policies/policy.json 
    networks:
      - keyvault:

volumes:
  vault-data: