version: "3.8"

services:
  vaultwarden:
    image: ${VAULTWARDEN_IMAGE}
    environment:
      - DISABLE_ADMIN_TOKEN=false
      - SIGNUPS_ALLOWED=false
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - DOMAIN=${DOMAIN}
    volumes:
      - vaultwarden:/data/
    restart: unless-stopped
    ports:
      - '${VAULTWARDEN_PORT}:80'
    networks:
      proxy:
      vaultwarden:
    security_opt:
      - no-new-privileges:true

volumes:
  vaultwarden:

networks:
  vaultwarden:
  proxy:
    external: true
