version: "3.8"

services:
  vaultwarden:
    image: ${VAULTWARDEN_IMAGE}
    volumes:
      - '/home/ubuntu/docker/vaultwarden/:/data/'
    restart: unless-stopped
    ports:
      - '${VAULTWARDEN_PORT}:80'
    networks:
      proxy:
      vaultwarden:
    security_opt:
      - no-new-privileges:true

networks:
  vaultwarden:
  proxy:
    external: true
