version: "3.8"

services:
  vaultwarden:
    image: ${VAULTWARDEN_IMAGE}
    environment:
      - SIGNUPS_ALLOWED=false
    volumes:
      - vaultwarden:/data/
    restart: unless-stopped
    ports:
      - '${VAULTWARDEN_PORT}:80'
    networks:
      proxy:
      vaultwarden:
    security_opt:
      - no-new-privileges:true

volumes:
  vaultwarden:

networks:
  vaultwarden:
  proxy:
    external: true

# sudo rm -rf /home/ubuntu/docker/vaultwarden/
